spring.application.name=wificsi-har-web

server.port=8080

# matlab.exe ???????????
matlab.bin=D:\\MATLAB2024B\\bin\\matlab.exe

# matlab??????????? matlab ????
matlab.projectDir=C:\\Users\\LENOVO\\Desktop\\WiFi-CSI-HAR-System\\matlab

# ???????????????????
matlab.backendOutputDir=C:\\WiFi-CSI-HAR-System\\backend\\src\\main\\resources\\outputs\\latest

